import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/EditableList.module.css'
import EditableList from '@/components/EditableList'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>One Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@1.*/css/pico.min.css" />
      </Head>
      <main>
        <h2 className={inter.className + ' ' + styles.section }>One Page</h2>
        <EditableList />
      </main>
    </>
  )
}
